spring:
  profiles:
    active: dev
  application:
    name: local-issues

server:
  servlet:
    context-path: /api/v1
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true

springdoc:
  default-produces-media-type: application/json

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}

