spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/insurance
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        use_sql_comments: true



server:
  port: 8090

