spring:
  datasource:
    url: jdbc:postgresql://localhost:54320/insurance
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      use_sql_comments: true
      format_sql: true
    properties:
      hibernate:
        format_sql: true
        SQL: debug
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8090

